/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ecnu_sei_manuzhang_nim_OpenGLJNILib */

#ifndef _Included_com_ecnu_sei_manuzhang_nim_OpenGLJNILib
#define _Included_com_ecnu_sei_manuzhang_nim_OpenGLJNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ecnu_sei_manuzhang_nim_OpenGLJNILib
 * Method:    onDrawFrame
 * Signature: (IIIFFI)V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_OpenGLJNILib_onDrawFrame
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jint);

/*
 * Class:     com_ecnu_sei_manuzhang_nim_OpenGLJNILib
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_OpenGLJNILib_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ecnu_sei_manuzhang_nim_OpenGLJNILib
 * Method:    onSurfaceCreated
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_OpenGLJNILib_onSurfaceCreated
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
