/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ecnu_sei_manuzhang_nim_GameViewRenderer */

#ifndef _Included_com_ecnu_sei_manuzhang_nim_GameViewRenderer
#define _Included_com_ecnu_sei_manuzhang_nim_GameViewRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ecnu_sei_manuzhang_nim_GameViewRenderer
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_GameViewRenderer_draw
  (JNIEnv *, jclass);

/*
 * Class:     com_ecnu_sei_manuzhang_nim_GameViewRenderer
 * Method:    generateTorus
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_GameViewRenderer_generateTorus
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

/*
 * Class:     com_ecnu_sei_manuzhang_nim_GameViewRenderer
 * Method:    generateCylinder
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_GameViewRenderer_generateCylinder
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
