/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ecnu_sei_manuzhang_nim_OpenGLJNILib */

#ifndef _Included_com_ecnu_sei_manuzhang_nim_OpenGLJNILib
#define _Included_com_ecnu_sei_manuzhang_nim_OpenGLJNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ecnu_sei_manuzhang_nim_OpenGLJNILib
 * Method:    onDrawFrame
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_OpenGLJNILib_onDrawFrame
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_ecnu_sei_manuzhang_nim_OpenGLJNILib
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_OpenGLJNILib_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ecnu_sei_manuzhang_nim_OpenGLJNILib
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ecnu_sei_manuzhang_nim_OpenGLJNILib_onSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_ecnu_sei_manuzhang_nim_OpenGLJNILib
 * Method:    onTorus
 * Signature: (FF)I
 */
JNIEXPORT jint JNICALL Java_com_ecnu_sei_manuzhang_nim_OpenGLJNILib_onTorus
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
